name: Deploy to EKS

on:
  workflow_dispatch:   # manual trigger
  push:
    branches: [ "main" ]

jobs:
  eks-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install eksctl
      run: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin
        eksctl version

    - name: Install kubectl
      run: |
        curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.29.0/2024-11-15/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/
        kubectl version --client

    - name: Create EKS cluster
      run: |
        eksctl create cluster \
          --name demo-cluster \
          --region $AWS_REGION \
          --nodes 2 \
          --node-type t3.medium

    - name: Deploy application
      run: |
        kubectl apply -f k8s-yaml/deployment.yaml
        kubectl apply -f k8s-yaml/service.yaml

    - name: Verify service
      run: |
        kubectl get svc demo-app-service
